wordList = [
    'arsenal',
    'aston villa',
    'brighton and hove albion',
    'burnley',
    'chelsea',
    'crystal palace',
    'everton',
    'fulham',
    'leeds united',
    'leicester city',
    'liverpool',
    'manchester city',
    'manchester united',
    'newcastle united',
    'sheffield united',
    'southampton',
    'tottenham hotspur',
    'west bromwich albion',
    'west ham united',
    'wolverhampton wanderers']
